import React, { createContext, useContext, useEffect, useState } from "react";
import Error from "@/components/ui/Error";

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

const translations = {
  en: {
    appName: "QRFlow Pro",
    home: "Home",
    createQR: "Create QR",
    scanQR: "Scan QR",
    about: "About",
    settings: "Settings",
    savedCodes: "Saved Codes",
    theme: "Theme",
    language: "Language",
    version: "Version",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    copyright: "© 2024 QRFlow Pro. All rights reserved.",
    welcomeTitle: "Advanced QR Code Tools",
    welcomeDescription: "Create and scan QR codes with advanced features and beautiful design",
    createQRTitle: "QR Code Generator",
    createQRDescription: "Generate QR codes for text, URLs, WiFi, and more",
    scanQRTitle: "QR Code Scanner",
    scanQRDescription: "Scan QR codes from camera or upload images",
    generate: "Generate",
    scan: "Scan",
    download: "Download",
    save: "Save",
    copy: "Copy",
    close: "Close",
    name: "Name",
    enterName: "Enter name for QR code",
    qrGenerated: "QR code generated successfully",
    qrScanned: "QR code scanned successfully",
    errorOccurred: "An error occurred",
    noQRFound: "No QR code found in image",
    text: "Text",
    url: "URL",
    wifi: "WiFi",
    contactCard: "Contact Card",
    enterText: "Enter text to encode",
    enterURL: "Enter URL",
    wifiSSID: "WiFi Network Name",
    wifiPassword: "WiFi Password",
    firstName: "First Name",
    lastName: "Last Name",
    phoneNumber: "Phone Number",
    email: "Email",
    uploadImage: "Upload Image",
    useCamera: "Use Camera",
    result: "Result",
    type: "Type",
    content: "Content",
    aboutTitle: "About QRFlow Pro",
    aboutDescription: "QRFlow Pro is a comprehensive QR code creation and scanning platform designed with cutting-edge technology and beautiful glassmorphism design.",
    features: "Features",
    usage: "How to Use",
    supportedLanguages: "Supported Languages",
    joinSupport: "Join Support Server",
    featuresList: [
      "Generate QR codes for text, URLs, WiFi credentials, and contact cards",
      "Scan QR codes using camera or by uploading images",
      "Download QR codes in multiple formats (PNG, JPG, JPEG, SVG)",
      "Beautiful glassmorphism design with smooth animations",
      "Multi-language support with RTL text direction",
      "Dark and light theme modes",
      "Responsive design for all devices"
    ],
    usageSteps: [
      "Select Create QR to generate new QR codes",
      "Choose the type of content you want to encode",
      "Fill in the required information",
      "Generate and download your QR code",
      "Use Scan QR to read existing QR codes",
      "Upload an image or use your camera to scan"
    ],
    languages: [
      "English",
      "العربية (Arabic)",
      "日本語 (Japanese)",
      "中文 (Chinese)",
      "한국어 (Korean)"
    ]
  },
  ar: {
    appName: "QRFlow Pro",
    home: "الرئيسية",
    createQR: "إنشاء QR",
    scanQR: "قراءة QR",
    about: "حول التطبيق",
    settings: "الإعدادات",
    savedCodes: "الرموز المحفوظة",
    theme: "المظهر",
    language: "اللغة",
    version: "الإصدار",
    privacyPolicy: "سياسة الخصوصية",
    termsOfService: "شروط الاستخدام",
    copyright: "© 2024 QRFlow Pro. جميع الحقوق محفوظة.",
    welcomeTitle: "أدوات QR متقدمة",
    welcomeDescription: "إنشاء وقراءة رموز QR بميزات متقدمة وتصميم جميل",
    createQRTitle: "منشئ رمز QR",
    createQRDescription: "إنشاء رموز QR للنصوص والروابط والواي فاي والمزيد",
    scanQRTitle: "قارئ رمز QR",
    scanQRDescription: "قراءة رموز QR من الكاميرا أو رفع الصور",
    generate: "إنشاء",
    scan: "قراءة",
    download: "تحميل",
    save: "حفظ",
    copy: "نسخ",
    close: "إغلاق",
    name: "الاسم",
    enterName: "أدخل اسماً لرمز QR",
    qrGenerated: "تم إنشاء رمز QR بنجاح",
    qrScanned: "تم قراءة رمز QR بنجاح",
    errorOccurred: "حدث خطأ",
    noQRFound: "لم يتم العثور على رمز QR في الصورة",
    text: "نص",
    url: "رابط",
    wifi: "واي فاي",
    contactCard: "بطاقة اتصال",
    enterText: "أدخل النص المراد تشفيره",
    enterURL: "أدخل الرابط",
    wifiSSID: "اسم شبكة الواي فاي",
    wifiPassword: "كلمة مرور الواي فاي",
    firstName: "الاسم الأول",
    lastName: "اسم العائلة",
    phoneNumber: "رقم الهاتف",
    email: "البريد الإلكتروني",
    uploadImage: "رفع صورة",
    useCamera: "استخدام الكاميرا",
    result: "النتيجة",
    type: "النوع",
    content: "المحتوى",
    aboutTitle: "حول QRFlow Pro",
    aboutDescription: "QRFlow Pro هو منصة شاملة لإنشاء وقراءة رموز QR مصممة بتقنية متطورة وتصميم glassmorphism جميل.",
    features: "الميزات",
    usage: "كيفية الاستخدام",
    supportedLanguages: "اللغات المدعومة",
    joinSupport: "انضم لخادم الدعم",
    featuresList: [
      "إنشاء رموز QR للنصوص والروابط وبيانات الواي فاي وبطاقات الاتصال",
      "قراءة رموز QR باستخدام الكاميرا أو رفع الصور",
      "تحميل رموز QR بصيغ متعددة (PNG, JPG, JPEG, SVG)",
      "تصميم glassmorphism جميل مع حركات سلسة",
      "دعم متعدد اللغات مع اتجاه النص من اليمين لليسار",
      "أوضاع المظهر المظلم والفاتح",
      "تصميم متجاوب لجميع الأجهزة"
    ],
    usageSteps: [
      "اختر إنشاء QR لتوليد رموز QR جديدة",
      "اختر نوع المحتوى الذي تريد تشفيره",
      "املأ المعلومات المطلوبة",
      "أنشئ وحمل رمز QR الخاص بك",
      "استخدم قراءة QR لقراءة رموز QR الموجودة",
      "ارفع صورة أو استخدم الكاميرا للقراءة"
    ],
    languages: [
      "English",
      "العربية (Arabic)",
      "日本語 (Japanese)",
      "中文 (Chinese)",
      "한국어 (Korean)"
    ]
  },
  ja: {
    appName: "QRFlow Pro",
    home: "ホーム",
    createQR: "QR作成",
    scanQR: "QRスキャン",
    about: "アプリについて",
    settings: "設定",
    savedCodes: "保存されたコード",
    theme: "テーマ",
    language: "言語",
    version: "バージョン",
    privacyPolicy: "プライバシーポリシー",
    termsOfService: "利用規約",
    copyright: "© 2024 QRFlow Pro. All rights reserved.",
    welcomeTitle: "高度なQRコードツール",
    welcomeDescription: "高度な機能と美しいデザインでQRコードを作成・スキャン",
    createQRTitle: "QRコードジェネレーター",
    createQRDescription: "テキスト、URL、WiFi、その他のQRコードを生成",
    scanQRTitle: "QRコードスキャナー",
    scanQRDescription: "カメラまたは画像アップロードでQRコードをスキャン",
    generate: "生成",
    scan: "スキャン",
    download: "ダウンロード",
    save: "保存",
    copy: "コピー",
    close: "閉じる",
    name: "名前",
    enterName: "QRコードの名前を入力",
    qrGenerated: "QRコードが正常に生成されました",
    qrScanned: "QRコードが正常にスキャンされました",
    errorOccurred: "エラーが発生しました",
    noQRFound: "画像にQRコードが見つかりません",
    text: "テキスト",
    url: "URL",
    wifi: "WiFi",
    contactCard: "連絡先カード",
    enterText: "エンコードするテキストを入力",
    enterURL: "URLを入力",
    wifiSSID: "WiFiネットワーク名",
    wifiPassword: "WiFiパスワード",
    firstName: "名",
    lastName: "姓",
    phoneNumber: "電話番号",
    email: "メール",
    uploadImage: "画像をアップロード",
    useCamera: "カメラを使用",
    result: "結果",
    type: "タイプ",
    content: "内容",
    aboutTitle: "QRFlow Proについて",
    aboutDescription: "QRFlow Proは最先端技術と美しいglassmorphismデザインで設計された包括的なQRコード作成・スキャンプラットフォームです。",
    features: "機能",
    usage: "使用方法",
    supportedLanguages: "対応言語",
    joinSupport: "サポートサーバーに参加",
    featuresList: [
      "テキスト、URL、WiFi認証情報、連絡先カードのQRコード生成",
      "カメラまたは画像アップロードでQRコードをスキャン",
      "複数形式でQRコードをダウンロード（PNG、JPG、JPEG、SVG）",
      "スムーズなアニメーションを備えた美しいglassmorphismデザイン",
      "RTLテキスト方向での多言語サポート",
      "ダークとライトのテーマモード",
      "すべてのデバイスに対応するレスポンシブデザイン"
    ],
    usageSteps: [
      "新しいQRコードを生成するには「QR作成」を選択",
      "エンコードしたいコンテンツのタイプを選択",
      "必要な情報を入力",
      "QRコードを生成してダウンロード",
      "既存のQRコードを読み取るには「QRスキャン」を使用",
      "画像をアップロードするかカメラを使用してスキャン"
    ],
    languages: [
      "English",
      "العربية (Arabic)",
      "日本語 (Japanese)",
      "中文 (Chinese)",
      "한국어 (Korean)"
    ]
  },
  zh: {
    appName: "QRFlow Pro",
    home: "首页",
    createQR: "创建二维码",
    scanQR: "扫描二维码",
    about: "关于应用",
    settings: "设置",
    savedCodes: "保存的代码",
    theme: "主题",
    language: "语言",
    version: "版本",
    privacyPolicy: "隐私政策",
    termsOfService: "服务条款",
    copyright: "© 2024 QRFlow Pro. 版权所有。",
    welcomeTitle: "高级二维码工具",
    welcomeDescription: "使用高级功能和精美设计创建和扫描二维码",
    createQRTitle: "二维码生成器",
    createQRDescription: "为文本、URL、WiFi等生成二维码",
    scanQRTitle: "二维码扫描器",
    scanQRDescription: "使用相机或上传图像扫描二维码",
    generate: "生成",
    scan: "扫描",
    download: "下载",
    save: "保存",
    copy: "复制",
    close: "关闭",
    name: "名称",
    enterName: "输入二维码名称",
    qrGenerated: "二维码生成成功",
    qrScanned: "二维码扫描成功",
    errorOccurred: "发生错误",
    noQRFound: "图像中未找到二维码",
    text: "文本",
    url: "网址",
    wifi: "WiFi",
    contactCard: "联系卡片",
    enterText: "输入要编码的文本",
    enterURL: "输入网址",
    wifiSSID: "WiFi网络名称",
    wifiPassword: "WiFi密码",
    firstName: "名",
    lastName: "姓",
    phoneNumber: "电话号码",
    email: "邮箱",
    uploadImage: "上传图像",
    useCamera: "使用相机",
    result: "结果",
    type: "类型",
    content: "内容",
    aboutTitle: "关于QRFlow Pro",
    aboutDescription: "QRFlow Pro是一个综合性的二维码创建和扫描平台，采用尖端技术和美丽的玻璃拟态设计。",
    features: "功能",
    usage: "使用方法",
    supportedLanguages: "支持的语言",
    joinSupport: "加入支持服务器",
featuresList: [
      "为文本、URL、WiFi凭据和联系卡片生成二维码",
      "使用相机或上传图像扫描二维码",
      "以多种格式下载二维码（PNG、JPG、JPEG、SVG）",
      "具有流畅动画的美丽玻璃拟态设计",
      "支持RTL文本方向的多语言支持",
      "深色和浅色主题模式",
      "适用于所有设备的响应式设计"
    ],
    usageSteps: [
      "选择'创建二维码'生成新的二维码",
      "选择要编码的内容类型",
      "填写所需信息",
      "生成并下载您的二维码",
      "使用'扫描二维码'读取现有二维码",
      "上传图像或使用相机进行扫描"
    ],
    languages: [
      "English",
      "العربية (Arabic)",
      "日本語 (Japanese)",
      "中文 (Chinese)",
      "한국어 (Korean)"
    ]
  },
  ko: {
    appName: "QRFlow Pro",
    home: "홈",
    createQR: "QR 생성",
    scanQR: "QR 스캔",
    about: "앱 정보",
    settings: "설정",
    savedCodes: "저장된 코드",
    theme: "테마",
    language: "언어",
    version: "버전",
    privacyPolicy: "개인정보 처리방침",
    termsOfService: "이용약관",
    copyright: "© 2024 QRFlow Pro. All rights reserved.",
    welcomeTitle: "고급 QR 코드 도구",
    welcomeDescription: "고급 기능과 아름다운 디자인으로 QR 코드 생성 및 스캔",
    createQRTitle: "QR 코드 생성기",
    createQRDescription: "텍스트, URL, WiFi 등을 위한 QR 코드 생성",
    scanQRTitle: "QR 코드 스캐너",
    scanQRDescription: "카메라 또는 이미지 업로드로 QR 코드 스캔",
    generate: "생성",
    scan: "스캔",
    download: "다운로드",
    save: "저장",
    copy: "복사",
    close: "닫기",
    name: "이름",
    enterName: "QR 코드 이름 입력",
    qrGenerated: "QR 코드가 성공적으로 생성되었습니다",
    qrScanned: "QR 코드가 성공적으로 스캔되었습니다",
    errorOccurred: "오류가 발생했습니다",
    noQRFound: "이미지에서 QR 코드를 찾을 수 없습니다",
    text: "텍스트",
    url: "URL",
    wifi: "WiFi",
    contactCard: "연락처 카드",
    enterText: "인코딩할 텍스트 입력",
    enterURL: "URL 입력",
    wifiSSID: "WiFi 네트워크 이름",
    wifiPassword: "WiFi 비밀번호",
    firstName: "이름",
    lastName: "성",
    phoneNumber: "전화번호",
    email: "이메일",
    uploadImage: "이미지 업로드",
    useCamera: "카메라 사용",
    result: "결과",
    type: "유형",
    content: "내용",
    aboutTitle: "QRFlow Pro 정보",
    aboutDescription: "QRFlow Pro는 최첨단 기술과 아름다운 글래스모피즘 디자인으로 설계된 포괄적인 QR 코드 생성 및 스캔 플랫폼입니다.",
    features: "기능",
    usage: "사용 방법",
    supportedLanguages: "지원 언어",
    joinSupport: "지원 서버 참여",
    featuresList: [
      "텍스트, URL, WiFi 자격 증명 및 연락처 카드용 QR 코드 생성",
      "카메라 또는 이미지 업로드로 QR 코드 스캔",
      "여러 형식으로 QR 코드 다운로드 (PNG, JPG, JPEG, SVG)",
      "부드러운 애니메이션을 갖춘 아름다운 글래스모피즘 디자인",
      "RTL 텍스트 방향을 지원하는 다국어 지원",
      "다크 및 라이트 테마 모드",
      "모든 기기에 대응하는 반응형 디자인"
    ],
    usageSteps: [
      "새 QR 코드를 생성하려면 'QR 생성' 선택",
      "인코딩하려는 콘텐츠 유형 선택",
      "필요한 정보 입력",
      "QR 코드 생성 및 다운로드",
      "기존 QR 코드를 읽으려면 'QR 스캔' 사용",
      "이미지를 업로드하거나 카메라를 사용하여 스캔"
    ],
    languages: [
      "English",
      "العربية (Arabic)",
      "日本語 (Japanese)",
      "中文 (Chinese)",
      "한국어 (Korean)"
    ]
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    const saved = localStorage.getItem("qrflow-language");
    return saved || "en";
  });

  useEffect(() => {
    localStorage.setItem("qrflow-language", language);
    document.documentElement.classList.toggle("rtl", language === "ar");
    document.documentElement.lang = language;
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const changeLanguage = (newLanguage) => {
    setLanguage(newLanguage);
  };

  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};